# Generated by Django 3.0.5 on 2025-05-27 01:31

import bson.objectid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('numero_orden', models.CharField(max_length=50)),
                ('fecha_emision', models.DateTimeField()),
                ('fecha_entrega_estimada', models.DateTimeField()),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True)),
                ('proveedor', djongo.models.fields.JSONField()),
                ('productos', djongo.models.fields.JSONField()),
                ('subtotal', models.IntegerField()),
                ('impuesto', models.IntegerField()),
                ('costo_envio', models.IntegerField()),
                ('total', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('metodo_pago', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Ordenes_Compra',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField()),
                ('cantidad_disponible', models.IntegerField()),
                ('imagen_url', models.CharField(blank=True, max_length=255, null=True)),
                ('categoria', models.CharField(choices=[('Alimento húmedo', 'Alimento húmedo'), ('Alimento seco', 'Alimento seco'), ('Juguete gato', 'Juguete gato'), ('Accesorio gato', 'Accesorio gato'), ('Juguete perro', 'Juguete perro'), ('Accesorio perro', 'Accesorio perro'), ('Medicamento gato', 'Medicamento gato'), ('Medicamento perro', 'Medicamento perro'), ('Vitamina gato', 'Vitamina gato'), ('Vitamina perro', 'Vitamina perro')], max_length=100)),
            ],
            options={
                'db_table': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', djongo.models.fields.JSONField()),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('catalogo', djongo.models.fields.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('numero_factura', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
                ('cliente', djongo.models.fields.JSONField()),
                ('productos', djongo.models.fields.JSONField()),
                ('metodo_pago', models.CharField(max_length=50)),
                ('subtotal', models.IntegerField()),
                ('impuesto', models.IntegerField()),
                ('total', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('rol', models.CharField(choices=[('Cliente', 'Cliente'), ('Administrador', 'Administrador')], default='Cliente', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', djongo.models.fields.JSONField()),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('historialCompras', djongo.models.fields.JSONField(blank=True, null=True)),
                ('preferencias', djongo.models.fields.JSONField(blank=True, default=dict)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Clientes',
            },
        ),
    ]